-include ../../../config.mk

SUBDIRS = common

SUBDIRS += cmpver
SUBDIRS += pkgpattern_match
SUBDIRS += plist_match
SUBDIRS += plist_match_virtual
SUBDIRS += util
SUBDIRS += find_pkg_orphans
SUBDIRS += pkgdb
SUBDIRS += config
SUBDIRS += shell
SUBDIRS += solve
SUBDIRS += version

include ../../../mk/subdir.mk
